/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Activitat`;

CREATE TABLE `Activitat` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `durada` INT NOT NULL)
 ENGINE=InnoDB;

ALTER TABLE `Activitat`
  ADD CONSTRAINT `Activitat_nom_fk`
    FOREIGN KEY (`nom`)
    REFERENCES `Experiencia` (`nom`)
    ON DELETE CASCADE;

