/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Categoria`;

CREATE TABLE `Categoria` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY)
 ENGINE=InnoDB;

