// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ESCAPADA_ODB_HXX
#define ESCAPADA_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Escapada.hxx"

#include "Categoria-odb.hxx"
#include "Experiencia-odb.hxx"

#include <memory>
#include <cstddef>
#include <string>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/polymorphic-info.hxx>
#include <odb/result.hxx>
#include <odb/polymorphic-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Escapada
  //
  template <>
  struct class_traits< ::Escapada >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Escapada >
  {
    public:
    typedef ::Escapada object_type;
    typedef ::std::shared_ptr< ::Escapada > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = true;

    typedef ::Experiencia root_type;
    typedef ::Experiencia base_type;
    typedef object_traits<root_type>::discriminator_type discriminator_type;
    typedef polymorphic_concrete_info<root_type> info_type;

    static const std::size_t depth = 2UL;

    typedef object_traits< ::Experiencia >::id_type id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      object_traits<root_type>::pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      root_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Escapada
  //
  template <typename A>
  struct query_columns< ::Escapada, id_mysql, A >:
    query_columns< ::Experiencia, id_mysql, typename A::base_traits >
  {
    // Experiencia
    //
    typedef query_columns< ::Experiencia, id_mysql, typename A::base_traits > Experiencia;

    // nom
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    nom_type_;

    static const nom_type_ nom;

    // hotel
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    hotel_type_;

    static const hotel_type_ hotel;

    // numNits
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    numNits_type_;

    static const numNits_type_ numNits;

    // preu
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        float,
        mysql::id_float >::query_type,
      mysql::id_float >
    preu_type_;

    static const preu_type_ preu;
  };

  template <typename A>
  const typename query_columns< ::Escapada, id_mysql, A >::nom_type_
  query_columns< ::Escapada, id_mysql, A >::
  nom (A::table_name, "`nom`", 0);

  template <typename A>
  const typename query_columns< ::Escapada, id_mysql, A >::hotel_type_
  query_columns< ::Escapada, id_mysql, A >::
  hotel (A::table_name, "`hotel`", 0);

  template <typename A>
  const typename query_columns< ::Escapada, id_mysql, A >::numNits_type_
  query_columns< ::Escapada, id_mysql, A >::
  numNits (A::table_name, "`numNits`", 0);

  template <typename A>
  const typename query_columns< ::Escapada, id_mysql, A >::preu_type_
  query_columns< ::Escapada, id_mysql, A >::
  preu (A::table_name, "`preu`", 0);

  template <typename A>
  struct pointer_query_columns< ::Escapada, id_mysql, A >:
    query_columns< ::Escapada, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Escapada, id_mysql >:
    public access::object_traits< ::Escapada >
  {
    public:
    typedef polymorphic_entry<object_type, id_mysql> entry_type;
    typedef object_traits_impl<root_type, id_mysql> root_traits;
    typedef object_traits_impl<base_type, id_mysql> base_traits;

    typedef root_traits::id_image_type id_image_type;

    static const info_type info;

    struct image_type
    {
      base_traits::image_type* base;

      // nom
      //
      details::buffer nom_value;
      unsigned long nom_size;
      my_bool nom_null;

      // hotel
      //
      details::buffer hotel_value;
      unsigned long hotel_size;
      my_bool hotel_null;

      // numNits
      //
      int numNits_value;
      my_bool numNits_null;

      // preu
      //
      float preu_value;
      my_bool preu_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static bool
    grow (image_type&,
          my_bool*,
          std::size_t = depth);

    static void
    bind (MYSQL_BIND*,
          const MYSQL_BIND* id,
          std::size_t id_size,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*,
          std::size_t = depth);

    static void
    init (id_image_type&, const id_type&);

    static bool
    check_version (const std::size_t*, const image_type&);

    static void
    update_version (std::size_t*, const image_type&, mysql::binding*);

    typedef
    mysql::polymorphic_derived_object_statements<object_type>
    statements_type;

    typedef
    mysql::polymorphic_root_object_statements<root_type>
    root_statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char* const find_statements[depth];
    static const std::size_t find_column_counts[depth];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&, bool top = true, bool dyn = true);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&, bool dyn = true);

    static bool
    reload (database&, object_type&, bool dyn = true);

    static void
    update (database&, const object_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const id_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const object_type&, bool top = true, bool dyn = true);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*,
           std::size_t = depth);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload,
           std::size_t = depth);

    static void
    load_ (database&, root_type&, std::size_t);
  };

  template <>
  class access::object_traits_impl< ::Escapada, id_common >:
    public access::object_traits_impl< ::Escapada, id_mysql >
  {
  };

  // Escapada
  //
}

#include "Escapada-odb.ixx"

#include <odb/post.hxx>

#endif // ESCAPADA_ODB_HXX
