/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Escapada`;

CREATE TABLE `Escapada` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `hotel` TEXT NOT NULL,
  `numNits` INT NOT NULL,
  `preu` FLOAT NOT NULL)
 ENGINE=InnoDB;

ALTER TABLE `Escapada`
  ADD CONSTRAINT `Escapada_nom_fk`
    FOREIGN KEY (`nom`)
    REFERENCES `Experiencia` (`nom`)
    ON DELETE CASCADE;

