/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Experiencia`;

CREATE TABLE `Experiencia` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `typeid` VARCHAR(128) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `ciutat` TEXT NOT NULL,
  `maximPlaces` INT NOT NULL,
  `preu` FLOAT NOT NULL,
  `dataAlta` TEXT NOT NULL,
  `numReserves` INT NOT NULL)
 ENGINE=InnoDB;

