// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "Experiencia-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy
#include <typeinfo>

#include <odb/polymorphic-map.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/polymorphic-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/polymorphic-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // Experiencia
  //

  struct access::object_traits_impl< ::Experiencia, id_mysql >::extra_statement_cache_type
  {
    mysql::container_statements_impl< categories_traits > categories;

    extra_statement_cache_type (
      mysql::connection& c,
      image_type&,
      id_image_type&,
      mysql::binding& id,
      mysql::binding&)
    : categories (c, id)
    {
    }
  };

  // categories
  //

  const char access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  select_statement[] =
  "SELECT "
  "`Experiencia_categories`.`index`, "
  "`Experiencia_categories`.`value` "
  "FROM `Experiencia_categories` "
  "WHERE `Experiencia_categories`.`object_id`=? ORDER BY `Experiencia_categories`.`index`";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  insert_statement[] =
  "INSERT INTO `Experiencia_categories` "
  "(`object_id`, "
  "`index`, "
  "`value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  delete_statement[] =
  "DELETE FROM `Experiencia_categories` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = d.value_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      d.value_value.capacity ());
    b[n].length = &d.value_size;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    if (t[1UL])
    {
      i.value_value.capacity (i.value_size);
      grew = true;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      typedef object_traits< ::Categoria > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& ptr_id (
          obj_traits::id (ptr_traits::get_ref (v)));

        std::size_t size (0);
        std::size_t cap (i.value_value.capacity ());
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_string >::set_image (
          i.value_value,
          size,
          is_null,
          ptr_id);
        i.value_null = is_null;
        i.value_size = static_cast<unsigned long> (size);
        grew = grew || (cap != i.value_value.capacity ());
      }
      else
        i.value_null = 1;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      typedef object_traits< ::Categoria > obj_traits;
      typedef odb::pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_string >::set_value (
          ptr_id,
          i.value_value,
          i.value_size,
          i.value_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (ptr_id));
      }
    }
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, sts.id_binding ().count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    st.cache ();
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      data_image_type& di (sts.data_image ());
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, id.count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::categories_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  access::object_traits_impl< ::Experiencia, id_mysql >::id_type
  access::object_traits_impl< ::Experiencia, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        id,
        i.nom_value,
        i.nom_size,
        i.nom_null);
    }

    return id;
  }

  access::object_traits_impl< ::Experiencia, id_mysql >::discriminator_type
  access::object_traits_impl< ::Experiencia, id_mysql >::
  discriminator (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    discriminator_type d;
    {
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        d,
        i.typeid_value,
        i.typeid_size,
        i.typeid_null);
    }

    return d;
  }

  bool access::object_traits_impl< ::Experiencia, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // nom
    //
    if (t[0UL])
    {
      i.nom_value.capacity (i.nom_size);
      grew = true;
    }

    // typeid_
    //
    if (t[1UL])
    {
      i.typeid_value.capacity (i.typeid_size);
      grew = true;
    }

    // descripcio
    //
    if (t[2UL])
    {
      i.descripcio_value.capacity (i.descripcio_size);
      grew = true;
    }

    // ciutat
    //
    if (t[3UL])
    {
      i.ciutat_value.capacity (i.ciutat_size);
      grew = true;
    }

    // maximPlaces
    //
    t[4UL] = 0;

    // dataAlta
    //
    if (t[5UL])
    {
      i.dataAlta_value.capacity (i.dataAlta_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // nom
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_STRING;
      b[n].buffer = i.nom_value.data ();
      b[n].buffer_length = static_cast<unsigned long> (
        i.nom_value.capacity ());
      b[n].length = &i.nom_size;
      b[n].is_null = &i.nom_null;
      n++;
    }

    // typeid_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_STRING;
      b[n].buffer = i.typeid_value.data ();
      b[n].buffer_length = static_cast<unsigned long> (
        i.typeid_value.capacity ());
      b[n].length = &i.typeid_size;
      b[n].is_null = &i.typeid_null;
      n++;
    }

    // descripcio
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.descripcio_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.descripcio_value.capacity ());
    b[n].length = &i.descripcio_size;
    b[n].is_null = &i.descripcio_null;
    n++;

    // ciutat
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.ciutat_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.ciutat_value.capacity ());
    b[n].length = &i.ciutat_size;
    b[n].is_null = &i.ciutat_null;
    n++;

    // maximPlaces
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.maximPlaces_value;
    b[n].is_null = &i.maximPlaces_null;
    n++;

    // dataAlta
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.dataAlta_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.dataAlta_value.capacity ());
    b[n].length = &i.dataAlta_size;
    b[n].is_null = &i.dataAlta_null;
    n++;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.id_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.id_value.capacity ());
    b[n].length = &i.id_size;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Experiencia, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // nom
    //
    if (sk == statement_insert)
    {
      ::std::string const& v =
        o.nom;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.nom_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.nom_value,
        size,
        is_null,
        v);
      i.nom_null = is_null;
      i.nom_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.nom_value.capacity ());
    }

    // typeid_
    //
    if (sk == statement_insert)
    {
      const info_type& di (map->find (typeid (o)));

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.typeid_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.typeid_value,
        size,
        is_null,
        di.discriminator);
      i.typeid_null = is_null;
      i.typeid_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.typeid_value.capacity ());
    }

    // descripcio
    //
    {
      ::std::string const& v =
        o.descripcio;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.descripcio_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.descripcio_value,
        size,
        is_null,
        v);
      i.descripcio_null = is_null;
      i.descripcio_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.descripcio_value.capacity ());
    }

    // ciutat
    //
    {
      ::std::string const& v =
        o.ciutat;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.ciutat_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.ciutat_value,
        size,
        is_null,
        v);
      i.ciutat_null = is_null;
      i.ciutat_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.ciutat_value.capacity ());
    }

    // maximPlaces
    //
    {
      int const& v =
        o.maximPlaces;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.maximPlaces_value, is_null, v);
      i.maximPlaces_null = is_null;
    }

    // dataAlta
    //
    {
      ::std::string const& v =
        o.dataAlta;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.dataAlta_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.dataAlta_value,
        size,
        is_null,
        v);
      i.dataAlta_null = is_null;
      i.dataAlta_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.dataAlta_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // nom
    //
    {
      ::std::string& v =
        o.nom;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.nom_value,
        i.nom_size,
        i.nom_null);
    }

    // descripcio
    //
    {
      ::std::string& v =
        o.descripcio;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.descripcio_value,
        i.descripcio_size,
        i.descripcio_null);
    }

    // ciutat
    //
    {
      ::std::string& v =
        o.ciutat;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.ciutat_value,
        i.ciutat_size,
        i.ciutat_null);
    }

    // maximPlaces
    //
    {
      int& v =
        o.maximPlaces;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i.maximPlaces_value,
        i.maximPlaces_null);
    }

    // dataAlta
    //
    {
      ::std::string& v =
        o.dataAlta;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.dataAlta_value,
        i.dataAlta_size,
        i.dataAlta_null);
    }
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        id);
      i.id_null = is_null;
      i.id_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  access::object_traits_impl< ::Experiencia, id_mysql >::map_type*
  access::object_traits_impl< ::Experiencia, id_mysql >::map;

  const access::object_traits_impl< ::Experiencia, id_mysql >::abstract_info_type
  access::object_traits_impl< ::Experiencia, id_mysql >::info (
    typeid (::Experiencia),
    0,
    0);

  const char access::object_traits_impl< ::Experiencia, id_mysql >::persist_statement[] =
  "INSERT INTO `Experiencia` "
  "(`nom`, "
  "`typeid`, "
  "`descripcio`, "
  "`ciutat`, "
  "`maximPlaces`, "
  "`dataAlta`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::find_statement[] =
  "SELECT "
  "`Experiencia`.`nom`, "
  "`Experiencia`.`typeid`, "
  "`Experiencia`.`descripcio`, "
  "`Experiencia`.`ciutat`, "
  "`Experiencia`.`maximPlaces`, "
  "`Experiencia`.`dataAlta` "
  "FROM `Experiencia` "
  "WHERE `Experiencia`.`nom`=?";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::
  find_discriminator_statement[] =
  "SELECT "
  "`Experiencia`.`typeid` "
  "FROM `Experiencia` "
  "WHERE `Experiencia`.`nom`=?";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::update_statement[] =
  "UPDATE `Experiencia` "
  "SET "
  "`descripcio`=?, "
  "`ciutat`=?, "
  "`maximPlaces`=?, "
  "`dataAlta`=? "
  "WHERE `nom`=?";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::erase_statement[] =
  "DELETE FROM `Experiencia` "
  "WHERE `nom`=?";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::query_statement[] =
  "SELECT "
  "`Experiencia`.`nom`, "
  "`Experiencia`.`typeid`, "
  "`Experiencia`.`descripcio`, "
  "`Experiencia`.`ciutat`, "
  "`Experiencia`.`maximPlaces`, "
  "`Experiencia`.`dataAlta` "
  "FROM `Experiencia`";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::erase_query_statement[] =
  "DELETE FROM `Experiencia`";

  const char access::object_traits_impl< ::Experiencia, id_mysql >::table_name[] =
  "`Experiencia`";

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  persist (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (top);

    using namespace mysql;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_persist, db, &obj, 0);
        return;
      }
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    id_image_type& i (sts.id_image ());
    init (i, id (obj));

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // categories
    //
    {
      ::std::vector< ::std::shared_ptr< ::Categoria > > const& v =
        obj.categories;

      categories_traits::persist (
        v,
        esc.categories);
    }
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  update (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    using namespace mysql;
    using mysql::update_statement;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_update, db, &obj, 0);
        return;
      }
    }

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // categories
    //
    {
      ::std::vector< ::std::shared_ptr< ::Categoria > > const& v =
        obj.categories;

      categories_traits::update (
        v,
        esc.categories);
    }
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  erase (database& db, const id_type& id, bool top, bool dyn)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (top);

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (dyn)
    {
      discriminator_type d;
      root_traits::discriminator_ (sts.root_statements (), id, &d);
      const info_type& pi (root_traits::map->find (d));

      if (!pi.derived (info))
        throw object_not_persistent ();

      pi.dispatch (info_type::call_erase, db, 0, &id);
      return;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // categories
    //
    {
      categories_traits::erase (
        esc.categories);
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  erase (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_erase, db, &obj, 0);
        return;
      }
    }

    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj), true, false);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::Experiencia, id_mysql >::pointer_type
  access::object_traits_impl< ::Experiencia, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    root_traits::discriminator_type d;

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
      d = root_traits::discriminator (sts.image ());
    }
    else
      root_traits::discriminator_ (sts, id, &d);

    const info_type& pi (root_traits::map->find (d));

    pointer_type p (pi.create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback_event ce (callback_event::pre_load);
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);

      if (&pi != &info)
      {
        std::size_t d (depth);
        pi.dispatch (info_type::call_load, db, &obj, &d);
      }

      sts.load_delayed (0);
      l.unlock ();
      ce = callback_event::post_load;
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position (), pi.delayed_loader);

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Experiencia, id_mysql >::
  find (database& db, const id_type& id, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace mysql;

    const std::type_info& t (typeid (obj));
    const info_type& pi (root_traits::map->find (t));
    return pi.dispatch (info_type::call_find, db, &obj, &id);
  }

  bool access::object_traits_impl< ::Experiencia, id_mysql >::
  reload (database& db, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace mysql;

    const std::type_info& t (typeid (obj));
    const info_type& pi (root_traits::map->find (t));
    return pi.dispatch (info_type::call_reload, db, &obj, 0);
  }

  bool access::object_traits_impl< ::Experiencia, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // categories
    //
    {
      ::std::vector< ::std::shared_ptr< ::Categoria > >& v =
        obj.categories;

      categories_traits::load (
        v,
        esc.categories);
    }
  }

  void access::object_traits_impl< ::Experiencia, id_mysql >::
  discriminator_ (statements_type& sts,
                  const id_type& id,
                  discriminator_type* pd)
  {
    using namespace mysql;

    id_image_type& idi (sts.discriminator_id_image ());
    init (idi, id);

    binding& idb (sts.discriminator_id_image_binding ());
    if (idi.version != sts.discriminator_id_image_version () ||
        idb.version == 0)
    {
      bind (idb.bind, idi);
      sts.discriminator_id_image_version (idi.version);
      idb.version++;
    }

    discriminator_image_type& i (sts.discriminator_image ());
    binding& imb (sts.discriminator_image_binding ());

    if (i.version != sts.discriminator_image_version () ||
        imb.version == 0)
    {
      MYSQL_BIND* b (imb.bind);
      std::size_t n (0);
      {
        b[n].buffer_type = MYSQL_TYPE_STRING;
        b[n].buffer = i.discriminator_value.data ();
        b[n].buffer_length = static_cast<unsigned long> (
          i.discriminator_value.capacity ());
        b[n].length = &i.discriminator_size;
        b[n].is_null = &i.discriminator_null;
      }

      sts.discriminator_image_version (i.version);
      imb.version++;
    }

    {
      select_statement& st (sts.find_discriminator_statement ());
      st.execute ();
      auto_result ar (st);
      select_statement::result r (st.fetch ());

      if (r == select_statement::no_data)
      {
        throw object_not_persistent ();
      }
      else if (r == select_statement::truncated)
      {
        bool grew (false);
        my_bool* t (sts.discriminator_image_truncated ());

        if (t[0UL])
        {
          i.discriminator_value.capacity (i.discriminator_size);
          grew = true;
        }

        if (grew)
          i.version++;

        if (i.version != sts.discriminator_image_version ())
        {
          MYSQL_BIND* b (imb.bind);
          std::size_t n (0);
          {
            b[n].buffer_type = MYSQL_TYPE_STRING;
            b[n].buffer = i.discriminator_value.data ();
            b[n].buffer_length = static_cast<unsigned long> (
              i.discriminator_value.capacity ());
            b[n].length = &i.discriminator_size;
            b[n].is_null = &i.discriminator_null;
          }

          sts.discriminator_image_version (i.version);
          imb.version++;
          st.refetch ();
        }
      }
    }

    if (pd != 0)
    {
      discriminator_type& d (*pd);
      {
        mysql::value_traits<
            ::std::string,
            mysql::id_string >::set_value (
          d,
          i.discriminator_value,
          i.discriminator_size,
          i.discriminator_null);
      }
    }
  }

  result< access::object_traits_impl< ::Experiencia, id_mysql >::object_type >
  access::object_traits_impl< ::Experiencia, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::polymorphic_object_result_impl<object_type> > r (
      new (shared) mysql::polymorphic_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Experiencia, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
