/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Reserva`;

CREATE TABLE `Reserva` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `numPlaces` INT NOT NULL,
  `preuPagat` FLOAT NOT NULL,
  `dataReserva` TEXT NOT NULL,
  `usuari` VARCHAR(128) NOT NULL,
  `experiencia` VARCHAR(128) NOT NULL)
 ENGINE=InnoDB;

ALTER TABLE `Reserva`
  ADD CONSTRAINT `Reserva_usuari_fk`
    FOREIGN KEY (`usuari`)
    REFERENCES `Usuari` (`username`),
  ADD CONSTRAINT `Reserva_experiencia_fk`
    FOREIGN KEY (`experiencia`)
    REFERENCES `Experiencia` (`nom`);

