// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef RESERVA_ODB_HXX
#define RESERVA_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Reserva.hxx"

#include "Experiencia-odb.hxx"
#include "Usuari-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Reserva
  //
  template <>
  struct class_traits< ::Reserva >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Reserva >
  {
    public:
    typedef ::Reserva object_type;
    typedef ::std::shared_ptr< ::Reserva > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Reserva
  //
  template <typename A>
  struct pointer_query_columns< ::Reserva, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // data
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    data_type_;

    static const data_type_ data;

    // numPlaces
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    numPlaces_type_;

    static const numPlaces_type_ numPlaces;

    // preuPagat
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        float,
        mysql::id_float >::query_type,
      mysql::id_float >
    preuPagat_type_;

    static const preuPagat_type_ preuPagat;

    // usuari
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    usuari_type_;

    static const usuari_type_ usuari;

    // experiencia
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    experiencia_type_;

    static const experiencia_type_ experiencia;
  };

  template <typename A>
  const typename pointer_query_columns< ::Reserva, id_mysql, A >::id_type_
  pointer_query_columns< ::Reserva, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Reserva, id_mysql, A >::data_type_
  pointer_query_columns< ::Reserva, id_mysql, A >::
  data (A::table_name, "`data`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Reserva, id_mysql, A >::numPlaces_type_
  pointer_query_columns< ::Reserva, id_mysql, A >::
  numPlaces (A::table_name, "`numPlaces`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Reserva, id_mysql, A >::preuPagat_type_
  pointer_query_columns< ::Reserva, id_mysql, A >::
  preuPagat (A::table_name, "`preuPagat`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Reserva, id_mysql, A >::usuari_type_
  pointer_query_columns< ::Reserva, id_mysql, A >::
  usuari (A::table_name, "`usuari`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Reserva, id_mysql, A >::experiencia_type_
  pointer_query_columns< ::Reserva, id_mysql, A >::
  experiencia (A::table_name, "`experiencia`", 0);

  template <>
  class access::object_traits_impl< ::Reserva, id_mysql >:
    public access::object_traits< ::Reserva >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      unsigned long long id_value;
      my_bool id_null;

      // data
      //
      details::buffer data_value;
      unsigned long data_size;
      my_bool data_null;

      // numPlaces
      //
      int numPlaces_value;
      my_bool numPlaces_null;

      // preuPagat
      //
      float preuPagat_value;
      my_bool preuPagat_null;

      // usuari
      //
      details::buffer usuari_value;
      unsigned long usuari_size;
      my_bool usuari_null;

      // experiencia
      //
      details::buffer experiencia_value;
      unsigned long experiencia_size;
      my_bool experiencia_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct usuari_tag;
    struct experiencia_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Reserva, id_common >:
    public access::object_traits_impl< ::Reserva, id_mysql >
  {
  };

  // Reserva
  //
  template <>
  struct alias_traits<
    ::Usuari,
    id_mysql,
    access::object_traits_impl< ::Reserva, id_mysql >::usuari_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Experiencia,
    id_mysql,
    access::object_traits_impl< ::Reserva, id_mysql >::experiencia_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Reserva, id_mysql >
  {
    // usuari
    //
    typedef
    odb::alias_traits<
      ::Usuari,
      id_mysql,
      access::object_traits_impl< ::Reserva, id_mysql >::usuari_tag>
    usuari_alias_;

    // experiencia
    //
    typedef
    odb::alias_traits<
      ::Experiencia,
      id_mysql,
      access::object_traits_impl< ::Reserva, id_mysql >::experiencia_tag>
    experiencia_alias_;
  };

  template <typename A>
  struct query_columns< ::Reserva, id_mysql, A >:
    query_columns_base< ::Reserva, id_mysql >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // data
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    data_type_;

    static const data_type_ data;

    // numPlaces
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    numPlaces_type_;

    static const numPlaces_type_ numPlaces;

    // preuPagat
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        float,
        mysql::id_float >::query_type,
      mysql::id_float >
    preuPagat_type_;

    static const preuPagat_type_ preuPagat;

    // usuari
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    usuari_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Usuari,
        id_mysql,
        usuari_alias_ > >
    usuari_pointer_type_;

    struct usuari_type_: usuari_pointer_type_, usuari_column_type_
    {
      usuari_type_ (const char* t, const char* c, const char* conv)
        : usuari_column_type_ (t, c, conv)
      {
      }
    };

    static const usuari_type_ usuari;

    // experiencia
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    experiencia_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Experiencia,
        id_mysql,
        experiencia_alias_ > >
    experiencia_pointer_type_;

    struct experiencia_type_: experiencia_pointer_type_, experiencia_column_type_
    {
      experiencia_type_ (const char* t, const char* c, const char* conv)
        : experiencia_column_type_ (t, c, conv)
      {
      }
    };

    static const experiencia_type_ experiencia;
  };

  template <typename A>
  const typename query_columns< ::Reserva, id_mysql, A >::id_type_
  query_columns< ::Reserva, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::Reserva, id_mysql, A >::data_type_
  query_columns< ::Reserva, id_mysql, A >::
  data (A::table_name, "`data`", 0);

  template <typename A>
  const typename query_columns< ::Reserva, id_mysql, A >::numPlaces_type_
  query_columns< ::Reserva, id_mysql, A >::
  numPlaces (A::table_name, "`numPlaces`", 0);

  template <typename A>
  const typename query_columns< ::Reserva, id_mysql, A >::preuPagat_type_
  query_columns< ::Reserva, id_mysql, A >::
  preuPagat (A::table_name, "`preuPagat`", 0);

  template <typename A>
  const typename query_columns< ::Reserva, id_mysql, A >::usuari_type_
  query_columns< ::Reserva, id_mysql, A >::
  usuari (A::table_name, "`usuari`", 0);

  template <typename A>
  const typename query_columns< ::Reserva, id_mysql, A >::experiencia_type_
  query_columns< ::Reserva, id_mysql, A >::
  experiencia (A::table_name, "`experiencia`", 0);
}

#include "Reserva-odb.ixx"

#include <odb/post.hxx>

#endif // RESERVA_ODB_HXX
