/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Usuari`;

CREATE TABLE `Usuari` (
  `username` VARCHAR(128) NOT NULL PRIMARY KEY,
  `nom` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `contrasenya` TEXT NOT NULL,
  `dataNaixement` TEXT NOT NULL)
 ENGINE=InnoDB;

