/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Usuari`;

CREATE TABLE `Usuari` (
  `sobrenom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `nom` TEXT NOT NULL,
  `correuElectronic` TEXT NOT NULL,
  `contrasenya` TEXT NOT NULL,
  `edat` INT NOT NULL)
 ENGINE=InnoDB;

