// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef USUARI_ODB_HXX
#define USUARI_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Usuari.hxx"

#include "Categoria-odb.hxx"
#include "Experiencia-odb.hxx"
#include "Reserva-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Usuari
  //
  template <>
  struct class_traits< ::Usuari >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Usuari >
  {
    public:
    typedef ::Usuari object_type;
    typedef ::std::shared_ptr< ::Usuari > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Usuari
  //
  template <typename A>
  struct query_columns< ::Usuari, id_mysql, A >
  {
    // username
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    username_type_;

    static const username_type_ username;

    // nom
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    nom_type_;

    static const nom_type_ nom;

    // email
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    email_type_;

    static const email_type_ email;

    // contrasenya
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    contrasenya_type_;

    static const contrasenya_type_ contrasenya;

    // dataNaixement
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    dataNaixement_type_;

    static const dataNaixement_type_ dataNaixement;
  };

  template <typename A>
  const typename query_columns< ::Usuari, id_mysql, A >::username_type_
  query_columns< ::Usuari, id_mysql, A >::
  username (A::table_name, "`username`", 0);

  template <typename A>
  const typename query_columns< ::Usuari, id_mysql, A >::nom_type_
  query_columns< ::Usuari, id_mysql, A >::
  nom (A::table_name, "`nom`", 0);

  template <typename A>
  const typename query_columns< ::Usuari, id_mysql, A >::email_type_
  query_columns< ::Usuari, id_mysql, A >::
  email (A::table_name, "`email`", 0);

  template <typename A>
  const typename query_columns< ::Usuari, id_mysql, A >::contrasenya_type_
  query_columns< ::Usuari, id_mysql, A >::
  contrasenya (A::table_name, "`contrasenya`", 0);

  template <typename A>
  const typename query_columns< ::Usuari, id_mysql, A >::dataNaixement_type_
  query_columns< ::Usuari, id_mysql, A >::
  dataNaixement (A::table_name, "`dataNaixement`", 0);

  template <typename A>
  struct pointer_query_columns< ::Usuari, id_mysql, A >:
    query_columns< ::Usuari, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Usuari, id_mysql >:
    public access::object_traits< ::Usuari >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      unsigned long id_size;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // username
      //
      details::buffer username_value;
      unsigned long username_size;
      my_bool username_null;

      // nom
      //
      details::buffer nom_value;
      unsigned long nom_size;
      my_bool nom_null;

      // email
      //
      details::buffer email_value;
      unsigned long email_size;
      my_bool email_null;

      // contrasenya
      //
      details::buffer contrasenya_value;
      unsigned long contrasenya_size;
      my_bool contrasenya_null;

      // dataNaixement
      //
      details::buffer dataNaixement_value;
      unsigned long dataNaixement_size;
      my_bool dataNaixement_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // reserves
    //
    struct reserves_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::std::shared_ptr< ::Reserva > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef mysql::container_statements< reserves_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        unsigned long long value_value;
        my_bool value_null;

        std::size_t version;
      };

      static void
      bind (MYSQL_BIND*,
            const MYSQL_BIND* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            my_bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Usuari, id_common >:
    public access::object_traits_impl< ::Usuari, id_mysql >
  {
  };

  // Usuari
  //
}

#include "Usuari-odb.ixx"

#include <odb/post.hxx>

#endif // USUARI_ODB_HXX
